colorScheme = "blowfish"
defaultTheme = "dark"
hotlinkFeatureImage = false
defaultBackgroundImage = "img/background.jpg"

[homepage]
  layout = "background"
  homepageImage = "img/background.jpg"
  showRecent = true
  showRecentItems = 6
  showMore = true
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true

[header]
  layout = "fixed"

[footer]
  showPoweredBy = true

[article]
  showDate = true
  showAuthor = false
  showHero = true
  heroStyle = "background"
  showTaxonomies = true
  showReadingTime = true
  layoutBackgroundBlur = false
  layoutBackgroundHeaderSpace = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = false
  layoutBackgroundHeaderSpace = true
  cardView = true
  groupByYear = false
  orderByWeight = true

enableSearch = true
